export enum LicenseHistoryEventTypeEnum {
  PURCHASE = 1,
  ACTIVATION = 2,
  ASSIGNMENT = 3,
  DEACTIVATION = 4,
  REVOCATION = 5,
  EXPIRATION = 6,
  EXTEND = 7,
  GRACE_PERIOD = 8,
  REDEMPTION_CODE_GENERATED = 9,
  REDEEMED = 10,
  REDEEM_CODE_REVOKED = 11,
  REDEEM_CODE_EXPIRED = 12,
}
