export enum DeviceLogActionEnum {
  SIGNED_IN = 1,
  SIGNED_OUT = 2,
  SESSION_REVOKED = 3,
  ACTIVATED = 4,
  DEACTIVATED = 5,
  ADMIN_SIGNED_IN = 6,
  ADMIN_SIGN_IN_FAILED = 7,
  TERMINAL_MAPPED = 8,
  TERMINAL_UNMAPPED = 9,
}
