export const orderSwaggerPaths = {
  // ========================================
  // ? DEVICE ORDERS (mounted /pvt/d/orders)
  // ========================================
  "/pvt/d/orders": {
    post: {
      tags: ["Orders"],
      summary: "Place a kiosk order and start its payment",
      description:
        "Prices the cart on the server from the current menu and branch tax profile, saves the order as PENDING_PAYMENT in the open business day with its token number, and starts a PhonePe UPI QR payment. Retrying with the same idempotencyKey returns the same order, and its QR while it is still valid. Only QR is supported for now. 409 BUSINESS_DAY_CLOSED while no business day is open.",
      security: [{ deviceCookieAuth: [] }],
      requestBody: {
        required: true,
        content: {
          "application/json": {
            schema: {
              type: "object",
              required: [
                "idempotencyKey",
                "orderType",
                "paymentMethod",
                "items",
              ],
              properties: {
                idempotencyKey: {
                  type: "string",
                  maxLength: 100,
                  description: "Generated by the device once per checkout",
                },
                orderType: {
                  type: "integer",
                  enum: [1, 2],
                  description: "OrderTypeEnum: 1 = DINE_IN, 2 = TAKEAWAY",
                },
                paymentMethod: {
                  type: "integer",
                  enum: [1, 2, 3],
                  description:
                    "TenantPaymentMethodEnum: 1 = QR, 2 = CARD, 3 = CASH",
                },
                items: {
                  type: "array",
                  minItems: 1,
                  maxItems: 50,
                  items: {
                    type: "object",
                    required: ["menuItemId", "quantity"],
                    properties: {
                      menuItemId: { type: "string", format: "uuid" },
                      quantity: { type: "integer", minimum: 1, maximum: 99 },
                      optionIds: {
                        type: "array",
                        items: { type: "string", format: "uuid" },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      responses: {
        "201": {
          description: "Order created with a pending QR payment",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  order: {
                    type: "object",
                    properties: {
                      id: { type: "string", format: "uuid" },
                      orderNumber: {
                        type: "string",
                        example: "ORD-260930-00A7K2",
                      },
                      tokenNumber: { type: "string", example: "042" },
                      orderStatus: { type: "integer", example: 1 },
                      currencyCode: { type: "string", example: "INR" },
                      totalAmount: { type: "string", example: "249.00" },
                    },
                  },
                  payment: {
                    type: "object",
                    properties: {
                      id: { type: "string", format: "uuid" },
                      paymentMethod: { type: "integer", example: 1 },
                      paymentStatus: { type: "integer", example: 1 },
                      amount: { type: "string", example: "249.00" },
                      qrData: { type: "string", nullable: true },
                      expiresAt: {
                        type: "string",
                        format: "date-time",
                        nullable: true,
                      },
                      expiresInSeconds: { type: "integer", example: 297 },
                      validForSeconds: { type: "integer", example: 300 },
                    },
                  },
                },
              },
            },
          },
        },
        "400": { $ref: "#/components/responses/ValidationError" },
        "401": { $ref: "#/components/responses/Unauthorized" },
        "403": { $ref: "#/components/responses/Forbidden" },
        "409": {
          description:
            "The order for this idempotency key was already processed",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/ErrorResponse" },
            },
          },
        },
      },
    },
  },

  // ========================================
  // ? USER ORDERS (mounted /pvt/u/orders)
  // ========================================
  "/pvt/u/orders": {
    get: {
      tags: ["Orders"],
      summary: "List orders (order history)",
      description:
        "Scoped by the effective tenant: an organization-scoped user sees every branch (optionally filtered by branchId), a branch-scoped user only their branch. Unpaid (PENDING_PAYMENT) orders are left out unless orderStatus asks for them.",
      parameters: [
        { $ref: "#/components/parameters/PageParam" },
        { $ref: "#/components/parameters/LimitParam" },
        {
          name: "search",
          in: "query",
          schema: { type: "string" },
          description: "Order number, or a token number (e.g. 42 or #042)",
        },
        {
          name: "branchId",
          in: "query",
          schema: { type: "string", format: "uuid" },
          description: "Organization scope only",
        },
        {
          name: "createdFrom",
          in: "query",
          schema: { type: "string", format: "date-time" },
        },
        {
          name: "createdTo",
          in: "query",
          schema: { type: "string", format: "date-time" },
        },
        {
          name: "orderStatus",
          in: "query",
          schema: { type: "integer", enum: [1, 2, 3, 4, 5, 6] },
          description:
            "OrderStatusEnum: 1 = PENDING_PAYMENT, 2 = PLACED, 3 = PREPARING, 4 = READY, 5 = COMPLETED, 6 = CANCELLED",
        },
        {
          name: "paymentStatus",
          in: "query",
          schema: { type: "integer", enum: [1, 2, 3, 4, 5] },
          description:
            "OrderPaymentStatusEnum: 1 = PENDING, 2 = COMPLETED, 3 = FAILED, 4 = REFUNDED, 5 = CANCELLED",
        },
        {
          name: "paymentMethod",
          in: "query",
          schema: { type: "integer", enum: [1, 2, 3] },
          description: "TenantPaymentMethodEnum: 1 = QR, 2 = CARD, 3 = CASH",
        },
        {
          name: "orderType",
          in: "query",
          schema: { type: "integer", enum: [1, 2] },
          description: "OrderTypeEnum: 1 = DINE_IN, 2 = TAKEAWAY",
        },
        {
          name: "sortBy",
          in: "query",
          schema: {
            type: "string",
            enum: ["createdAt", "orderNumber", "totalAmount"],
          },
        },
        {
          name: "sortOrder",
          in: "query",
          schema: { type: "string", enum: ["asc", "desc"] },
        },
      ],
      responses: {
        "200": {
          description: "Paginated orders",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  orders: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        id: { type: "string", format: "uuid" },
                        orderNumber: { type: "string" },
                        tokenNumber: { type: "string", example: "042" },
                        branchId: { type: "string", format: "uuid" },
                        branchName: { type: "string" },
                        branchTimezone: { type: "string", nullable: true },
                        orderType: { type: "integer" },
                        orderSource: { type: "integer" },
                        orderStatus: { type: "integer" },
                        paymentStatus: { type: "integer" },
                        paymentMethod: { type: "integer", nullable: true },
                        currencyCode: { type: "string" },
                        totalAmount: { type: "string" },
                        itemCount: { type: "integer" },
                        createdAt: { type: "string", format: "date-time" },
                      },
                    },
                  },
                  total: { type: "integer" },
                  page: { type: "integer" },
                  limit: { type: "integer" },
                  totalPages: { type: "integer" },
                },
              },
            },
          },
        },
        "400": { $ref: "#/components/responses/ValidationError" },
        "401": { $ref: "#/components/responses/Unauthorized" },
        "403": { $ref: "#/components/responses/Forbidden" },
      },
    },
  },
  "/pvt/u/orders/live-counts": {
    get: {
      tags: ["Orders"],
      summary: "Order counts per status for the current business day",
      description:
        "Branch scope only: the request must carry a branch (an organization user has to switch into one). Counts that branch's PLACED, PREPARING, READY and COMPLETED orders of the open business day (or today's, once closed).",
      parameters: [
        {
          name: "orderType",
          in: "query",
          schema: { type: "integer", enum: [1, 2] },
        },
      ],
      responses: {
        "200": {
          description: "Order counts per status",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  placed: { type: "integer" },
                  preparing: { type: "integer" },
                  ready: { type: "integer" },
                  completed: { type: "integer" },
                },
              },
            },
          },
        },
        "400": { $ref: "#/components/responses/ValidationError" },
        "401": { $ref: "#/components/responses/Unauthorized" },
        "403": { $ref: "#/components/responses/Forbidden" },
      },
    },
  },
};
