export const orderSwaggerPaths = {
  // ========================================
  // ? DEVICE ORDERS (mounted /pvt/d/orders)
  // ========================================
  "/pvt/d/orders": {
    post: {
      tags: ["Orders"],
      summary: "Place a kiosk order and start its payment",
      description:
        "Prices the cart on the server from the current menu and branch tax profile, saves the order as PENDING_PAYMENT with a daily token number, and starts a PhonePe UPI QR payment. Retrying with the same idempotencyKey returns the same order, and its QR while it is still valid. Only QR is supported for now.",
      security: [{ deviceCookieAuth: [] }],
      requestBody: {
        required: true,
        content: {
          "application/json": {
            schema: {
              type: "object",
              required: [
                "idempotencyKey",
                "orderType",
                "paymentMethod",
                "items",
              ],
              properties: {
                idempotencyKey: {
                  type: "string",
                  maxLength: 100,
                  description: "Generated by the device once per checkout",
                },
                orderType: {
                  type: "integer",
                  enum: [1, 2],
                  description: "OrderTypeEnum: 1 = DINE_IN, 2 = TAKEAWAY",
                },
                paymentMethod: {
                  type: "integer",
                  enum: [1, 2, 3],
                  description:
                    "TenantPaymentMethodEnum: 1 = QR, 2 = CARD, 3 = CASH",
                },
                items: {
                  type: "array",
                  minItems: 1,
                  maxItems: 50,
                  items: {
                    type: "object",
                    required: ["menuItemId", "quantity"],
                    properties: {
                      menuItemId: { type: "string", format: "uuid" },
                      quantity: { type: "integer", minimum: 1, maximum: 99 },
                      optionIds: {
                        type: "array",
                        items: { type: "string", format: "uuid" },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      responses: {
        "201": {
          description: "Order created with a pending QR payment",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  order: {
                    type: "object",
                    properties: {
                      id: { type: "string", format: "uuid" },
                      orderNumber: {
                        type: "string",
                        example: "ORD-260930-00A7K2",
                      },
                      tokenNumber: { type: "string", example: "042" },
                      orderStatus: { type: "integer", example: 1 },
                      currencyCode: { type: "string", example: "INR" },
                      totalAmount: { type: "string", example: "249.00" },
                    },
                  },
                  payment: {
                    type: "object",
                    properties: {
                      id: { type: "string", format: "uuid" },
                      paymentMethod: { type: "integer", example: 1 },
                      paymentStatus: { type: "integer", example: 1 },
                      amount: { type: "string", example: "249.00" },
                      qrData: { type: "string", nullable: true },
                      expiresAt: {
                        type: "string",
                        format: "date-time",
                        nullable: true,
                      },
                    },
                  },
                },
              },
            },
          },
        },
        "400": { $ref: "#/components/responses/ValidationError" },
        "401": { $ref: "#/components/responses/Unauthorized" },
        "403": { $ref: "#/components/responses/Forbidden" },
        "409": {
          description:
            "The order for this idempotency key was already processed",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/ErrorResponse" },
            },
          },
        },
      },
    },
  },
};
