export const orderSwaggerPaths = {
  // ========================================
  // ? DEVICE ORDERS (mounted /pvt/d/orders)
  // ========================================
  "/pvt/d/orders": {
    post: {
      tags: ["Orders"],
      summary: "Place a kiosk order and start its payment",
      description:
        "Prices the cart on the server from the current menu and branch tax profile and saves the order as PENDING_PAYMENT in the open business day. With paymentMethod QR (1) it starts a PhonePe UPI QR payment and returns it; the token number is given once that payment completes, and retrying with the same idempotencyKey returns the same order and its QR while still valid. With paymentMethod CASH (3), on a counter device only, the signed-in staff member takes the money now: the order is saved as PLACED and paid with its token, `payment` is null, and retrying with the same idempotencyKey returns that same order. Counter orders record the staff member in created_by and the payment in collected_by. With isPayAtCounter true the order gets its token straight away, has no payment method yet, stays PENDING_PAYMENT until the counter takes the money, and `payment` is null; it is cancelled if the business day closes before it is paid. 409 BUSINESS_DAY_CLOSED while no business day is open, or ORDERS_PAUSED while new orders are on hold.",
      security: [{ deviceCookieAuth: [] }],
      requestBody: {
        required: true,
        content: {
          "application/json": {
            schema: {
              type: "object",
              required: ["idempotencyKey", "orderType", "items"],
              properties: {
                idempotencyKey: {
                  type: "string",
                  maxLength: 100,
                  description: "Generated by the device once per checkout",
                },
                orderType: {
                  type: "integer",
                  enum: [1, 2],
                  description: "OrderTypeEnum: 1 = DINE_IN, 2 = TAKEAWAY",
                },
                isPayAtCounter: {
                  type: "boolean",
                  default: false,
                  description:
                    "The customer pays at the counter instead of on the device",
                },
                paymentMethod: {
                  type: "integer",
                  enum: [1, 2, 3],
                  description:
                    "TenantPaymentMethodEnum: 1 = QR, 2 = CARD, 3 = CASH. Required unless isPayAtCounter is true; QR on every device and CASH on a counter are supported for now",
                },
                items: {
                  type: "array",
                  minItems: 1,
                  maxItems: 50,
                  items: {
                    type: "object",
                    required: ["menuItemId", "quantity"],
                    properties: {
                      menuItemId: { type: "string", format: "uuid" },
                      quantity: { type: "integer", minimum: 1, maximum: 99 },
                      optionIds: {
                        type: "array",
                        items: { type: "string", format: "uuid" },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      responses: {
        "201": {
          description:
            "Order created with a pending QR payment, or placed straight away when paid in cash on a counter",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  order: {
                    type: "object",
                    properties: {
                      id: { type: "string", format: "uuid" },
                      orderNumber: {
                        type: "string",
                        example: "ORD-260930-00A7K2",
                      },
                      tokenNumber: {
                        type: "string",
                        example: "042",
                        nullable: true,
                        description: "Given when the order is paid",
                      },
                      orderStatus: { type: "integer", example: 1 },
                      currencyCode: { type: "string", example: "INR" },
                      totalAmount: { type: "string", example: "249.00" },
                    },
                  },
                  payment: {
                    type: "object",
                    properties: {
                      id: { type: "string", format: "uuid" },
                      paymentMethod: { type: "integer", example: 1 },
                      paymentStatus: { type: "integer", example: 1 },
                      amount: { type: "string", example: "249.00" },
                      qrData: { type: "string", nullable: true },
                      expiresAt: {
                        type: "string",
                        format: "date-time",
                        nullable: true,
                      },
                      expiresInSeconds: { type: "integer", example: 297 },
                      validForSeconds: { type: "integer", example: 300 },
                    },
                  },
                },
              },
            },
          },
        },
        "400": { $ref: "#/components/responses/ValidationError" },
        "401": { $ref: "#/components/responses/Unauthorized" },
        "403": { $ref: "#/components/responses/Forbidden" },
        "409": {
          description:
            "The order for this idempotency key was already processed",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/ErrorResponse" },
            },
          },
        },
      },
    },
  },

  "/pvt/d/orders/pending-payments": {
    get: {
      tags: ["Orders"],
      summary: "List pay-at-counter orders waiting for payment (counter)",
      description:
        "Counter devices only, with a signed-in staff member. Returns the pay-at-counter orders of the current business day that are still PENDING_PAYMENT, by token number, a page at a time. `total` is the number of matching orders. Counter devices in the branch get the socket event order.pending-payments.changed whenever this list changes: a kiosk places a pay-at-counter order, or one is paid or cancelled at a counter.",
      security: [{ deviceCookieAuth: [] }],
      parameters: [
        { $ref: "#/components/parameters/PageParam" },
        { $ref: "#/components/parameters/LimitParam" },
        {
          name: "search",
          in: "query",
          schema: { type: "string" },
          description: "Order number, or a token number (e.g. 42 or #042)",
        },
      ],
      responses: {
        "200": {
          description: "Orders waiting for payment at the counter",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  orders: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        id: { type: "string", format: "uuid" },
                        orderNumber: { type: "string" },
                        tokenNumber: { type: "integer", example: 7 },
                        orderType: { type: "integer", enum: [1, 2] },
                        currencyCode: { type: "string", example: "INR" },
                        totalAmount: { type: "string", example: "354.90" },
                        itemCount: { type: "integer" },
                        createdAt: { type: "string", format: "date-time" },
                      },
                    },
                  },
                  total: { type: "integer" },
                  page: { type: "integer" },
                  limit: { type: "integer" },
                  totalPages: { type: "integer" },
                },
              },
            },
          },
        },
      },
    },
  },

  "/pvt/d/orders/{id}/payments": {
    post: {
      tags: ["Orders"],
      summary: "Take the payment for a pay-at-counter order (counter)",
      description:
        "Counter devices only. With paymentMethod CASH (3) the signed-in staff member takes the money now: the order becomes PLACED and keeps the token it was given on the kiosk, `payment` is null, and repeating the call returns the same order. With paymentMethod QR (1) it starts a PhonePe UPI QR payment for the order and returns it (the still-valid QR is returned again on a repeat); the order is placed when that payment completes. The staff member is recorded in collected_by. 409 when the order is not a pay-at-counter order waiting for payment.",
      security: [{ deviceCookieAuth: [] }],
      parameters: [
        {
          name: "id",
          in: "path",
          required: true,
          schema: { type: "string", format: "uuid" },
        },
      ],
      requestBody: {
        required: true,
        content: {
          "application/json": {
            schema: {
              type: "object",
              required: ["paymentMethod"],
              properties: {
                paymentMethod: {
                  type: "integer",
                  enum: [1, 3],
                  description: "TenantPaymentMethodEnum: 1 = QR, 3 = CASH",
                },
              },
            },
          },
        },
      },
      responses: {
        "200": {
          description:
            "The order, with the QR payment to show or null when paid in cash (same shape as placing an order)",
        },
        "404": {
          description: "Order not found in this branch",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/ErrorResponse" },
            },
          },
        },
        "409": {
          description: "The order was already paid or cancelled",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/ErrorResponse" },
            },
          },
        },
      },
    },
  },

  "/pvt/d/orders/{id}/cancel": {
    post: {
      tags: ["Orders"],
      summary: "Cancel a pay-at-counter order before it is paid (counter)",
      description:
        "Counter devices only. Cancels a pay-at-counter order that is still PENDING_PAYMENT and records the signed-in staff member. 409 when the order was already paid or cancelled.",
      security: [{ deviceCookieAuth: [] }],
      parameters: [
        {
          name: "id",
          in: "path",
          required: true,
          schema: { type: "string", format: "uuid" },
        },
      ],
      responses: {
        "200": { description: "Order cancelled" },
        "409": {
          description: "The order can no longer be cancelled",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/ErrorResponse" },
            },
          },
        },
      },
    },
  },

  // ========================================
  // ? USER ORDERS (mounted /pvt/u/orders)
  // ========================================
  "/pvt/u/orders": {
    get: {
      tags: ["Orders"],
      summary: "List orders (order history)",
      description:
        "Scoped by the effective tenant: an organization-scoped user sees every branch (optionally filtered by branchId), a branch-scoped user only their branch. Unpaid (PENDING_PAYMENT) orders are left out unless orderStatus asks for them.",
      parameters: [
        { $ref: "#/components/parameters/PageParam" },
        { $ref: "#/components/parameters/LimitParam" },
        {
          name: "search",
          in: "query",
          schema: { type: "string" },
          description: "Order number, or a token number (e.g. 42 or #042)",
        },
        {
          name: "branchId",
          in: "query",
          schema: { type: "string", format: "uuid" },
          description: "Organization scope only",
        },
        {
          name: "createdFrom",
          in: "query",
          schema: { type: "string", format: "date-time" },
        },
        {
          name: "createdTo",
          in: "query",
          schema: { type: "string", format: "date-time" },
        },
        {
          name: "orderStatus",
          in: "query",
          schema: { type: "integer", enum: [1, 2, 3, 4, 5, 6] },
          description:
            "OrderStatusEnum: 1 = PENDING_PAYMENT, 2 = PLACED, 3 = PREPARING, 4 = READY, 5 = COMPLETED, 6 = CANCELLED",
        },
        {
          name: "paymentStatus",
          in: "query",
          schema: { type: "integer", enum: [1, 2, 3, 4, 5] },
          description:
            "OrderPaymentStatusEnum: 1 = PENDING, 2 = COMPLETED, 3 = FAILED, 4 = REFUNDED, 5 = CANCELLED",
        },
        {
          name: "paymentMethod",
          in: "query",
          schema: { type: "integer", enum: [1, 2, 3] },
          description: "TenantPaymentMethodEnum: 1 = QR, 2 = CARD, 3 = CASH",
        },
        {
          name: "orderType",
          in: "query",
          schema: { type: "integer", enum: [1, 2] },
          description: "OrderTypeEnum: 1 = DINE_IN, 2 = TAKEAWAY",
        },
        {
          name: "sortBy",
          in: "query",
          schema: {
            type: "string",
            enum: ["createdAt", "orderNumber", "totalAmount"],
          },
        },
        {
          name: "sortOrder",
          in: "query",
          schema: { type: "string", enum: ["asc", "desc"] },
        },
      ],
      responses: {
        "200": {
          description: "Paginated orders",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  orders: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        id: { type: "string", format: "uuid" },
                        orderNumber: { type: "string" },
                        tokenNumber: {
                          type: "string",
                          example: "042",
                          nullable: true,
                          description: "Given when the order is paid",
                        },
                        branchId: { type: "string", format: "uuid" },
                        branchName: { type: "string" },
                        branchTimezone: { type: "string", nullable: true },
                        orderType: { type: "integer" },
                        orderSource: { type: "integer" },
                        orderStatus: { type: "integer" },
                        paymentStatus: { type: "integer" },
                        paymentMethod: { type: "integer", nullable: true },
                        currencyCode: { type: "string" },
                        totalAmount: { type: "string" },
                        itemCount: { type: "integer" },
                        createdAt: { type: "string", format: "date-time" },
                      },
                    },
                  },
                  total: { type: "integer" },
                  page: { type: "integer" },
                  limit: { type: "integer" },
                  totalPages: { type: "integer" },
                },
              },
            },
          },
        },
        "400": { $ref: "#/components/responses/ValidationError" },
        "401": { $ref: "#/components/responses/Unauthorized" },
        "403": { $ref: "#/components/responses/Forbidden" },
      },
    },
  },
  "/pvt/u/orders/live-counts": {
    get: {
      tags: ["Orders"],
      summary: "Order counts per status for the current business day",
      description:
        "Branch scope only: the request must carry a branch (an organization user has to switch into one). Counts that branch's PLACED, PREPARING, READY and COMPLETED orders of the open business day (or today's, once closed).",
      parameters: [
        {
          name: "orderType",
          in: "query",
          schema: { type: "integer", enum: [1, 2] },
        },
      ],
      responses: {
        "200": {
          description: "Order counts per status",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  placed: { type: "integer" },
                  preparing: { type: "integer" },
                  ready: { type: "integer" },
                  completed: { type: "integer" },
                },
              },
            },
          },
        },
        "400": { $ref: "#/components/responses/ValidationError" },
        "401": { $ref: "#/components/responses/Unauthorized" },
        "403": { $ref: "#/components/responses/Forbidden" },
      },
    },
  },
};
