export const VALIDATION_CONSTANTS = {
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 64,
  USERS_NAME_MIN_LENGTH: 2,
  USERS_NAME_MAX_LENGTH: 100,
  MOBILE_MIN_LENGTH: 10,
  MOBILE_MAX_LENGTH: 20,
} as const;
